spring.jpa.show-sql=true

# POSTGRESQL
spring.sql.init.platform=postgresql

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${LEXICONLAIR_PG_URL:jdbc:postgresql://localhost:5432/lexiconlair}
spring.datasource.username=${LEXICONLAIR_PG_USERNAME:lexiconlair-user}
spring.datasource.password=${LEXICONLAIR_PG_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=true
