spring.jpa.show-sql=true

# MYSQL
spring.sql.init.platform=mysql

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${LEXICONLAIR_MYSQL_URL:jdbc:mysql://localhost:3306/lexiconlair}
spring.datasource.username=${LEXICONLAIR_MYSQL_USERNAME:lexiconlair-user}
spring.datasource.password=${LEXICONLAIR_MYSQL_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

