spring.jpa.show-sql=true

spring.sql.init.platform=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.datasource.url=${BACKEND_PG_URL:jdbc:postgresql://localhost:5432/backend}
spring.datasource.username=${BACKEND_PG_USERNAME:backend-user}
spring.datasource.password=${BACKEND_PG_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
