server.port=8080
#spring.mvc.view.prefix=/src/main/resources/META-INF/resources/WEB-INF/jsp
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework=INFO
logging.level.com.ronanos.com.goodwords=INFO
spring.mvc.format.date=yyyy-MM-dd
# spring.profiles.active=mysql
spring.profiles.active=postgresql

# Force creation of items in schema.sql and data.sql in non in memory databases. HSQL db etc will have this by default. 
# MySQL, PostGres etc will not.
# spring.sql.init.mode=always This forces Spring Boot to search for and execute initialization scripts (like data.sql) even if you are not using an embedded database.
spring.sql.init.mode=always
# spring.jpa.hibernate.ddl-auto=none  (or validate/update): This tells Hibernate not to create the schema, allowing your existing database structure to remain intact.
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.defer-datasource-initialization=true: This is critical if you want your data.sql to run after Hibernate has finished its startup sequence. It ensures tables exist before the data script attempts to insert rows.
spring.jpa.defer-datasource-initialization=true


